# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
#        fos_userbundle:
#            id: fos_user.user_provider.username
        certificate:
            id: emercoin.security.certificate.provider
#            memory:
#                users:
#                    azhuravlov@aspanta.com:
#                        roles: ROLE_SUPER_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        certificate:
            pattern: ^/
            x509:
                provider: certificate
            anonymous: ~

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            x509:
                provider: certificate

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false

#             # activate different ways to authenticate
#             http_basic: ~
#             http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#             form_login: ~
#             http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/, roles: [ ROLE_USER, IS_AUTHENTICATED_ANONYMOUSLY ], requires_channel: https }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/api/v2/token, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
